# Generated by Django 5.0.6 on 2024-05-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='agreeRate',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='disagreeRate',
        ),
    ]
